version: '3'
services:
  # Spring Boot Application
  redis_assignment_api:
    container_name: redis_assignment_api
    restart: always
    build:
      context: ./redis_assignment_api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - local-network

  redis_assignment_ui:
    container_name: redis_assignment_ui
    restart: always
    build:
      context: ./redis_assignment_ui
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    networks:
      - local-network

  redis_db:
    image: redis/redis-stack-server:latest
    container_name: redis_db
    ports:
      - "6379:6378"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data
    networks:
      - local-network

networks:
  local-network:
    driver: bridge

volumes:
  redis_data: